# Generated by Django 5.2.6 on 2025-09-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('address', models.CharField(max_length=300, verbose_name='Endereço')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(max_length=100, verbose_name='Estado')),
                ('zip_code', models.CharField(max_length=20, verbose_name='CEP')),
                ('bedrooms', models.IntegerField(verbose_name='Quartos')),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Banheiros')),
                ('area', models.IntegerField(verbose_name='Área (m²)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='Imagem')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponível')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
                'ordering': ['-created_at'],
            },
        ),
    ]
