# Generated by Django 5.2.6 on 2025-09-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Número do WhatsApp (ex: 5511999999999)', max_length=20, null=True, verbose_name='WhatsApp'),
        ),
    ]
