# Generated by Django 5.2.6 on 2025-09-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0004_newslettersignup'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rental_type',
            field=models.CharField(choices=[('compra', 'Compra'), ('aluguel', 'Aluguel')], default='compra', max_length=20, verbose_name='Tipo de Locação'),
        ),
    ]
